### ISSUE TITLE
App crashes on load (THREE.WebGLRenderer: EXT_blend_minmax extension not supported)

### ISSUE THREAD

**Issue by XavierMod** [CodyJasonBennett/r3f-native-starter#4]
Hi! Thanks for building this, it's awesome. I'm having this error when loading the app:

THREE.WebGLRenderer: EXT_blend_minmax extension not supported. at node_modules/three/build/three.js:12511:5 in get at node_modules/three/build/three.js:15905:21 in WebGLState at node_modules/three/build/three.js:18835:11 in initGLContext at node_modules/three/build/three.js:18866:15 in WebGLRenderer at node_modules/@react-three/fiber/dist/index-ff3eb68b.cjs.dev.js:1609:19 in createRendererInstance at node_modules/@react-three/fiber/dist/index-ff3eb68b.cjs.dev.js:1672:49 in render at node_modules/@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js:330:4 in React__namespace.forwardRef$argument_0

Then it crashes.

Any suggestions?

**Comment by CodyJasonBennett** [comment]
Can you share a repo for me to look at? I'd need to see where three is failing.

**Comment by hrstrand** [comment]
I am seeing the exact same - with unmodified repo r3f-native-starter.
Using an mac m1 -- not sure it would make a difference?

Let me know if I can assist in any further logging or debugging

**Comment by CodyJasonBennett** [comment]
I can't recreate the crash behavior, but three should handle extensions gracefully. expo-gl gives us a WebGL 2 context where this extension is native so this warning looks out of place.

I'd need to see the full stack trace to dig any further.

**Comment by slbateman** [comment]
Not sure if this helps, I'm quite new, but this is what I'm getting:
![Screen Shot 2022-01-27 at 5 20 39 PM](https://user-images.githubusercontent.com/91349879/151465272-156cf0a1-729e-4f95-b037-633cb5080fbe.png)

Then the THREE.MeshStandardMaterial error repeats about 15 times before it crashes.
Here's what the app looks like when it crashes:
![Screen Shot 2022-01-27 at 5 20 55 PM](https://user-images.githubusercontent.com/91349879/151465631-a114fa1c-cbbf-453e-aead-064e5b8e6f6a.png)

**Comment by Entryist** [comment]
Same crash behavior here.

```
iOS Bundling complete 53ms
iOS Running app on iPhone 13
EXGL: gl.pixelStorei() doesn't support this parameter yet!
EXGL: gl.pixelStorei() doesn't support this parameter yet!
EXGL: gl.pixelStorei() doesn't support this parameter yet!

THREE.WebGLRenderer: EXT_color_buffer_float extension not supported.
at node_modules/three/build/three.js:12511:5 in get
at node_modules/three/build/three.js:16401:4 in getInternalFormat
at node_modules/three/build/three.js:16663:41 in uploadTexture
at node_modules/three/build/three.js:16525:18 in setTexture2D
at node_modules/three/build/three.js:17211:15 in safeSetTexture2D
at node_modules/three/build/three.js:13338:2 in setValueT1
at node_modules/three/build/three.js:13792:4 in WebGLUniforms.upload
at node_modules/three/build/three.js:19828:4 in setProgram
at node_modules/three/build/three.js:19159:29 in renderBufferDirect
at node_modules/three/build/three.js:19556:5 in renderObject
at node_modules/three/build/three.js:19526:17 in renderObjects
at node_modules/three/build/three.js:19478:46 in renderScene
at node_modules/three/build/three.js:19356:15 in render
at node_modules/@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js:212:19 in state.gl.render
at node_modules/three/build/three.js:11822:3 in PMREMGenerator#_textureToCubeUV
at node_modules/three/build/three.js:11683:3 in PMREMGenerator#_fromTexture
at node_modules/three/build/three.js:12398:44 in get
at node_modules/three/build/three.js:19663:18 in setProgram
at node_modules/three/build/three.js:19159:29 in renderBufferDirect
at node_modules/three/build/three.js:19556:5 in renderObject
at node_modules/three/build/three.js:19526:17 in renderObjects
at node_modules/three/build/three.js:19478:46 in renderScene
at node_modules/three/build/three.js:19356:15 in render
at node_modules/@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js:212:19 in state.gl.render
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1482:51 in render$1
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1504:26 in roots.forEach$argument_0
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1498:4 in loop
```

**Comment by CodyJasonBennett** [comment]
NPM had some issues earlier but we rolled out a patch in `8.0.0-beta.0` (was beta-05).

Can you update and see if this persists and which three versions are affected?

**Comment by slbateman** [comment]
Still see same error in IOS, Android seems to work fine:

"dependencies": {
    "@react-three/drei": "^8.0.0",
    "@react-three/fiber": "^8.0.0-beta.0",
    "expo": "^44.0.6",
    "expo-gl": "~11.1.1",
    "react": "^18.0.0-rc.0",
    "react-native": "0.64.3",
    "three": "0.133.1"
  }

THREE.WebGLRenderer: EXT_color_buffer_float extension not supported.
at node_modules/three/build/three.js:12511:5 in get
at node_modules/three/build/three.js:16401:4 in getInternalFormat
at node_modules/three/build/three.js:16663:41 in uploadTexture
at node_modules/three/build/three.js:16525:18 in setTexture2D
at node_modules/three/build/three.js:17211:15 in safeSetTexture2D
at node_modules/three/build/three.js:13338:2 in setValueT1
at node_modules/three/build/three.js:13792:4 in WebGLUniforms.upload
at node_modules/three/build/three.js:19828:4 in setProgram
at node_modules/three/build/three.js:19159:29 in renderBufferDirect
at node_modules/three/build/three.js:19556:5 in renderObject
at node_modules/three/build/three.js:19526:17 in renderObjects
at node_modules/three/build/three.js:19478:46 in renderScene
at node_modules/three/build/three.js:19356:15 in render
at node_modules/@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js:212:19 in state.gl.render
at node_modules/three/build/three.js:11822:3 in PMREMGenerator#_textureToCubeUV
at node_modules/three/build/three.js:11683:3 in PMREMGenerator#_fromTexture
at node_modules/three/build/three.js:12398:44 in get
at node_modules/three/build/three.js:19663:18 in setProgram
at node_modules/three/build/three.js:19159:29 in renderBufferDirect
at node_modules/three/build/three.js:19556:5 in renderObject
at node_modules/three/build/three.js:19526:17 in renderObjects
at node_modules/three/build/three.js:19478:46 in renderScene
at node_modules/three/build/three.js:19356:15 in render
at node_modules/@react-three/fiber/native/dist/react-three-fiber-native.cjs.dev.js:212:19 in state.gl.render
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1482:51 in render$1
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1504:26 in roots.forEach$argument_0
at node_modules/@react-three/fiber/dist/index-95c17855.cjs.dev.js:1498:4 in loop

**Comment by CodyJasonBennett** [comment]
Which devices are you testing on? IOS version?

**Comment by slbateman** [comment]
via Simulator on an iPhone 13 running ios 15.2, 
Then on a physical iPhone XS running ios 15.1.
The Android I'm using is a physical Pixel 3XL, running Android 12 (works)

**Comment by XiongMeng1992** [comment]
I have the same problem, it doesn't work on iPhone 13, it works on Android

**Comment by XiongMeng1992** [comment]
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/40554573/184099749-71c13294-4c92-48af-bd12-101b78ae06f5.png">
@CodyJasonBennett This error still occurs when I try to load GLB with maps. Is there a solution for this? Thank you very much.

**Comment by carmenchapa** [comment]
> <img alt="image" width="1384" src="https://user-images.githubusercontent.com/40554573/184099749-71c13294-4c92-48af-bd12-101b78ae06f5.png">
> 
> @CodyJasonBennett This error still occurs when I try to load GLB with maps. Is there a solution for this? Thank you very much.

Hey @XiongMeng1992,  would you mind to elaborate what do you mean by GLB with maps? I keep getting crashes in production with every glb file except for the one in the example and I can't figure out why (I barley know anything about 3D..)

**Comment by CodyJasonBennett** [comment]
Maps would refer to textures. It's particularly problematic when embedding them into a GLB over the filesystem since react-native doesn't implement some web APIs needed to unpack them. See https://github.com/pmndrs/react-three-fiber/issues/1972.

**Comment by carmenchapa** [comment]
Thanks a lot for the quick response. I saw that issue and I've been trying to export basic models from blender without textures with no luck, even opening the example file in blender and exporting it again fails. Obviously, this is a 3D problem and here is not the place to ask for this, I apologise for that. But, could I ask where the iphone.glb file did originally came from? maybe this is somehow helpful.
Note: I also have the same problem when using OBJ, I render couple of files as in this repo [example](https://github.com/alexandrius/react-native_3d_store) and work ok in development but crashes on prod

**Comment by CodyJasonBennett** [comment]
The model comes from my former projects, there's a whole bunch in https://github.com/CodyJasonBennett/device-models/tree/master/design. I don't export with any sort of DRACO compression, but I've kept them relatively low poly for performance reasons. The issue with assets loading in dev and not prod sounds like a deeper issue. I might refer you to https://github.com/pmndrs/react-three-fiber/issues/2577 which I haven't investigated yet but will be actively looking into.

**Comment by carmenchapa** [comment]
Thank you, I will play around with the rest of the models, see if I get more insights.
Will put my logs in that other issue in case is helpful.
