### ISSUE TITLE
OrbitControls component which was imported from @react-three/drei/native dosen't work

### ISSUE THREAD

**Issue by Andy-Leo** [CodyJasonBennett/r3f-native-starter#6]
I need OrbitControls component to control my camera. 

![rn-error](https://user-images.githubusercontent.com/14280000/160289115-3032fe92-655b-4e1a-b0b3-a5c62dd79860.png)

My android sdk is version 10.0

**Comment by CodyJasonBennett** [comment]
OrbitControls and modules from three/examples assume a DOM context. I don't think we can support those.

There are controls like PresentationControls that rely on virtual gestures via use-gesture. Haven't implemented react-native support there but it would be pretty simple.
